### ISSUE TITLE
Old festivals removed from search

### ISSUE THREAD

**Issue by youngtag** [domurtag/festivals#24]
Can you allow old festivals to be viewed in search please...I can't clone old festivals, so I need to be able to find those festivals to make that short cut.

I'm going to have to add some festivals and keep the site ticking over to some extent for the summer given this job I'm doing for Feidhlim. It's fairly urgent, so if you could look at it whenever you get a chance that would be appreciated.

**Comment by domurtag** [comment]
I'd rather not add finished to be included in the search results because this will reintroduce the problem that removing them solved. 

In case you don't remember what this problem is: as time goes on, the number of finished festivals increases steadily while the number of future festivals remains fairly constant. If finished festivals are included in the search results, they dominate future festivals, but in general users are only interested in the latter. So if finished festivals are included in the search results indefinitely, the data becomes dominated by irrelevant data. So the current approach is to remove festivals from the search results once the festival is 6 months old.

However, you can still access these festivals from the festival list page once you uncheck the "Future Festivals Only" box. So you could load a list of all Irish/UK/European festivals, and then use the browser's search feature (Ctrl + F) to search for the festival by name. Is this an acceptable compromise?

**Comment by domurtag** [comment]
Closing this due to non-response.
